/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controledeestoque.view;

import controledeestoque.controller.RelatorioDeEstoque;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelControleDeEstoque = new javax.swing.JLabel();
        tabbedPaneCentral = new javax.swing.JTabbedPane();
        buttonInserirProdutos = new javax.swing.JButton();
        buttonBaixarProdutos = new javax.swing.JButton();
        buttonRelatorioDeEstoque = new javax.swing.JButton();
        buttonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelControleDeEstoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelControleDeEstoque.setText("Controle de Estoque");

        buttonInserirProdutos.setText("Inserir Produtos");
        buttonInserirProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserirProdutosActionPerformed(evt);
            }
        });

        buttonBaixarProdutos.setText("Baixar Produtos");
        buttonBaixarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBaixarProdutosActionPerformed(evt);
            }
        });

        buttonRelatorioDeEstoque.setText("Relatorio de Estoque");
        buttonRelatorioDeEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatorioDeEstoqueActionPerformed(evt);
            }
        });

        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(labelControleDeEstoque))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(buttonInserirProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBaixarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(buttonRelatorioDeEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tabbedPaneCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelControleDeEstoque)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInserirProdutos)
                    .addComponent(buttonBaixarProdutos)
                    .addComponent(buttonRelatorioDeEstoque)
                    .addComponent(buttonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPaneCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Deseja mesmo fechar o sistema","Confirmaçao", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonInserirProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserirProdutosActionPerformed
        // TODO add your handling code here:
        tabbedPaneCentral.removeAll();
        tabbedPaneCentral.add("Inserir Produtos", new InserirProdutosView());
        tabbedPaneCentral.validate();
        tabbedPaneCentral.repaint();
    }//GEN-LAST:event_buttonInserirProdutosActionPerformed

    private void buttonBaixarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBaixarProdutosActionPerformed
        // TODO add your handling code here:
        tabbedPaneCentral.removeAll();
        tabbedPaneCentral.add("Baixar Produtos", new BaixarProdutosView());
        tabbedPaneCentral.validate();
        tabbedPaneCentral.repaint();
    }//GEN-LAST:event_buttonBaixarProdutosActionPerformed

    private void buttonRelatorioDeEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatorioDeEstoqueActionPerformed
        // TODO add your handling code here:
        try{
        Date data = new Date();
        DateFormat df = new SimpleDateFormat("DD__MM__YYYY");
        RelatorioDeEstoque relatorioEstoque = new RelatorioDeEstoque("Documentos" + "Relatorio_de_Estoque" + df.format(data)+".pdf");
        if (relatorioEstoque.geraRelatorio()){
            JOptionPane.showMessageDialog(this, "Relatorio gerado com sucesso! O relatorio" +" gerado se encontra em Documentos", "Sucesso",JOptionPane.OK_OPTION);
            
        } else{
            JOptionPane.showMessageDialog(this,"Relatorio nao gerado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
     }  catch(Exception e){
         Logger.getLogger(PrincipalView.class.getName()).log(Level.SEVERE, null, e);
     }
    }//GEN-LAST:event_buttonRelatorioDeEstoqueActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBaixarProdutos;
    private javax.swing.JButton buttonInserirProdutos;
    private javax.swing.JButton buttonRelatorioDeEstoque;
    private javax.swing.JButton buttonSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelControleDeEstoque;
    private javax.swing.JTabbedPane tabbedPaneCentral;
    // End of variables declaration//GEN-END:variables
}
